// <auto-generated />
using System;
using InmobiliariaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobiliariaBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302222712_MigracionBaseCompleta")]
    partial class MigracionBaseCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InmobiliariaBackend.Models.PedidoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion_problema");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("direccion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pedido");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("localidad");

                    b.Property<string>("OficioRequerido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("oficio_requerido");

                    b.Property<int>("PropiedadId")
                        .HasColumnType("int")
                        .HasColumnName("propiedad_id");

                    b.HasKey("Id");

                    b.ToTable("pedidos_servicio", (string)null);
                });

            modelBuilder.Entity("InmobiliariaBackend.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Ambientes")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoInmueble")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_inmueble");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_operacion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("propiedades", (string)null);
                });

            modelBuilder.Entity("InmobiliariaBackend.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cuil");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Oficios")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("oficios");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("InmobiliariaBackend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("InmobiliariaBackend.Models.Propiedad", b =>
                {
                    b.HasOne("InmobiliariaBackend.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
