// <auto-generated />
using System;
using InmobiliariaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobiliariaBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219220223_AgregarTablaServicios")]
    partial class AgregarTablaServicios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InmobiliariaBackend.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Ambientes")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoInmueble")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_inmueble");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.ToTable("propiedades", (string)null);
                });

            modelBuilder.Entity("InmobiliariaBackend.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cuil");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Oficios")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("oficios");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.ToTable("servicios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
